#!/usr/bin/env zsh

source "$HOME/.bashrc"

# Enable Powerlevel10k instant prompt. Should stay close to the top of ~/.zshrc.
# Initialization code that may require console input (password prompts, [y/n]
# confirmations, etc.) must go above this block; everything else may go below.
if [[ -r "$XDG_CACHE_HOME/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "$XDG_CACHE_HOME/p10k-instant-prompt-${(%):-%n}.zsh"
fi

# Download Znap, if it's not there yet.
[[ -r "$XDG_DATA_HOME/znap/znap/znap.zsh" ]] ||
  git clone --depth=1 https://github.com/marlonrichert/zsh-snap.git "$XDG_DATA_HOME/znap/znap"
source "$XDG_DATA_HOME/znap/znap/znap.zsh"  # Start Znap

# Prompt
znap source romkatv/powerlevel10k

# Completions
znap install zsh-users/zsh-completions

# Keybindings
znap source belak/zsh-utils editor

# History
znap source belak/zsh-utils history

# Utilities
znap source belak/zsh-utils utility

# # Other Fish-like features
znap source zdharma-continuum/fast-syntax-highlighting  # Syntax highlighting
znap source zsh-users/zsh-autosuggestions               # Auto-suggestions
znap source zsh-users/zsh-history-substring-search      # Up/Down to search history

if zmodload zsh/terminfo && (( terminfo[colors] >= 256 )); then
  [[ ! -f ~/.p10k.d/gui.zsh ]] || source ~/.p10k.d/gui.zsh
else
  [[ ! -f ~/.p10k.d/cui.zsh ]] || source ~/.p10k.d/cui.zsh
fi

# 履歴ファイルに保存される履歴の件数
export SAVEHIST=100000000
# メモリに保存される履歴の件数
export HISTSIZE=1000000

# Options
# https://zsh.sourceforge.io/Doc/Release/Options.html

setopt extendedglob
setopt nobeep

# Allow comments even in interactive shells.
setopt interactive_comments

# Append a trailing ‘/’ to all directory names resulting from filename generation (globbing).
setopt mark_dirs

# When the current word has a glob pattern, do not insert all the words resulting from the expansion but generate matches as for completion and cycle through them like MENU_COMPLETE. The matches are generated as if a ‘*’ was added to the end of the word, or inserted at the cursor when COMPLETE_IN_WORD is set. This actually uses pattern matching, not globbing, so it works not only for files but for any completion, such as options, user names, etc.
# Note that when the pattern matcher is used, matching control (for example, case-insensitive or anchored matching) cannot be used. This limitation only applies when the current word contains a pattern; simply turning on the GLOB_COMPLETE option does not have this effect.
setopt glob_complete

# If a parameter name was completed and a following character (normally a space) automatically inserted, and the next character typed is one of those that have to come directly after the name (like ‘}’, ‘:’, etc.), the automatically added character is deleted, so that the character typed comes immediately after the parameter name. Completion in a brace expansion is affected similarly: the added character is a ‘,’, which will be removed if ‘}’ is typed next.
setopt auto_param_keys

# If a parameter is completed whose content is the name of a directory, then add a trailing slash instead of a space.
setopt auto_param_slash

# emacsベースの新しいキーマップ
bindkey -N modified emacs
bindkey -A modified main

# 変数とかglobを展開しない
bindkey -M modified "^I" complete-word

# history-substring-search
bindkey -M modified '^[OA' history-substring-search-up
bindkey -M modified '^[OB' history-substring-search-down

