#!/bin/sh
#
#
# ~/.xinitrc
#
# Executed by startx (run your window manager from here)

userresources=$HOME/.Xresources
usermodmap=$HOME/.Xmodmap
sysresources=/etc/X11/xinit/.Xresources
sysmodmap=/etc/X11/xinit/.Xmodmap

export LANG=ja_JP.UTF-8
export LC_NUMERIC=ja_JP.UTF-8
export LC_TIME=ja_JP.UTF-8
export LC_MONETARY=ja_JP.UTF-8
export LC_PAPER=ja_JP.UTF-8
export LC_MEASUREMENT=ja_JP.UTF-8

# merge in defaults and keymaps

if [ -f $sysresources ]; then
    xrdb -merge $sysresources
fi

if [ -f $sysmodmap ]; then
    xmodmap $sysmodmap
fi

if [ -f "$userresources" ]; then
    xrdb -merge "$userresources"
fi

if [ -f "$usermodmap" ]; then
    xmodmap "$usermodmap"
fi

# start some nice programs

if [ -d /etc/X11/xinit/xinitrc.d ] ; then
    for f in /etc/X11/xinit/xinitrc.d/?*.sh ; do
        [ -x "$f" ] && . "$f"
    done
    unset f
fi

if [ -f ~/.xprofile ]; then
    . ~/.xprofile
fi

# source ~/.bashrc

# Keyring daemon
# gnome-keyring-daemon --start --components=pkcs11 &

kbdrate -d 400 -r 50
xset r rate 400 50
xset s 3600 3600

xsetroot -cursor_name left_ptr &

xhost +SI:localuser:$USER &

xrandr --setprovideroutputsource 1 0 &
#xrandr --setprovideroutputsource modesetting NVIDIA-0
xrandr --auto &
# xrandr --output HDMI-A-0 --scale 1.125
# xrandr --dpi 192

# export QT_AUTO_SCREEN_SCALE_FACTOR=0
# export QT_SCALE_FACTOR=1.125

# export GTK_IM_MODULE=uim
# export XMODIFIERS=@im=uim
# export QT_IM_MODULE=uim

# export GTK_IM_MODULE=fcitx
# export QT_IM_MODULE=fcitx
# export XMODIFIERS=@im=fcitx

export GTK_IM_MODULE=ibus
export XMODIFIERS=@im=ibus
export QT_IM_MODULE=ibus

export EDITOR='code --wait'

# export QT_QPA_PLATFORMTHEME='gtk2'
export QT_QPA_PLATFORMTHEME='qt5ct'
# export QT_STYLE_OVERRID='kvantum'

# copied from startlxde
if [ -z "$XDG_CONFIG_HOME" ]; then
	export XDG_CONFIG_HOME="$HOME/.config"
fi

if [ -z "$XDG_DATA_HOME" ]; then
	export XDG_DATA_HOME="$HOME/.local/share"
fi

# Ensure the existance of the 'Desktop' folder
if [ -e "$XDG_CONFIG_HOME/user-dirs.dirs" ]; then
	. "$XDG_CONFIG_HOME/user-dirs.dirs"
else
	XDG_DESKTOP_DIR="$HOME/Desktop"
fi
mkdir -p "$XDG_DESKTOP_DIR"

# Ensure the existance of the user applications folder
USER_APPS_DIR="$XDG_DATA_HOME/applications"
mkdir -p "$USER_APPS_DIR"

# Clean up after GDM (GDM sets the number of desktops to one)
xprop -root -remove _NET_NUMBER_OF_DESKTOPS -remove _NET_DESKTOP_NAMES -remove _NET_CURRENT_DESKTOP 2> /dev/null

# Enable GTK+2 integration for OpenOffice.org, if available.
export SAL_USE_VCLPLUGIN=gtk

# Launch DBus if needed
if test -z "$DBUS_SESSION_BUS_ADDRESS"; then
	if which dbus-launch >/dev/null; then
		eval "$(dbus-launch --sh-syntax --exit-with-session)"
	fi
else
	if which dbus-update-activation-environment >/dev/null; then
		dbus-update-activation-environment --systemd --all
	fi
fi

# #/usr/lib/mate-polkit/polkit-mate-authentication-agent-1
# # /usr/lib/polkit-kde-authentication-agent-1 &
# # lxqt-policykit-agent &
# /usr/lib/xfce-polkit/xfce-polkit &

# dunst &

# picom --experimental-backends &

# export TERM=xterm-256color

# fcitx5 &

# uim-xim &

# uim-toolbar-gtk3-systray &

# greenclip daemon &

# pasystray &

# sh ~/.screenlayout/default.sh &

# uim-toolbar-gtk

sh ~/tablet.sh &

# feh --bg-scale /usr/share/wallpapers/FallenLeaf/contents/images/2560x1600.jpg &

# tint2 &

# memeclock &

# alacritty &
# wezterm &

# pavucontrol &

# firefox &
