#!/bin/sh
set -e
IFS='
'
SHARED_GIT_DIR=$XDG_DATA_HOME/git

prepared() {
    [ "$GIT_DIR" = "$SHARED_GIT_DIR" ] && return || true
    while { IFS=' '; read -r _ new ref; } do
        refname=$(printf '%s\n' "$ref" | cut -d/ -f2-)
        namespace=refs/namespaces/$(echo "$GIT_DIR" | sed -E 's:/?\.git/?$::; s:^.*/::; s:[[:blank:]]:_:g')
        if { echo "$new" | grep '^ref:'; } then
            git -C "$SHARED_GIT_DIR" symbolic-ref "$namespace/$refname" "$namespace/$(echo "$new" | sed 's!^ref:refs/!!')"
        else
            git -C "$SHARED_GIT_DIR" update-ref "$namespace/$refname" "$new"
        fi
    done
    return
}

committed() {
    return
}

aborted() {
    return
}

case "$1" in
    prepared) prepared;;
    committed) committed;;
    aborted) aborted;;
esac

