# alacritty.toml

live_config_reload = true

[env]
TERM = "xterm-256color"
LANG = "en_US.UTF-8"
LANGUAGE = "en_US.UTF-8"

[font]
size = 8.0

[colors]
draw_bold_text_with_bright_colors = true

[colors.primary]
background = "0x000000"
foreground = "0xB3B1AD"

[colors.normal]
black = "0x000000"
red = "0xcd0000"
green = "0x00cd00"
yellow = "0xcdcd00"
blue = "0x0000ee"
magenta = "0xcd00cd"
cyan = "0x00cdcd"
white = "0xe5e5e5"

[colors.bright]
black = "0x7f7f7f"
red = "0xff0000"
green = "0x00ff00"
yellow = "0xffff00"
blue = "0x5c5cff"
magenta = "0xff00ff"
cyan = "0x00ffff"
white = "0xffffff"

[bell]
duration = 250

[selection]
save_to_clipboard = true

[cursor]
unfocused_hollow = true
